# Generated by Django 5.1.3 on 2024-12-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_smallwin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallwin',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
